name: Build and Upload Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          rust-version: stable

      - name: Build Rust Release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Release Build
          path: target/release/

